import "./globals.css";
import Providers from "./provider";
import { getThemeLayout } from "./themeConfig";
import { Metadata } from 'next';
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const currentTheme = "theme2";
  const Layout = getThemeLayout(currentTheme);
  return (
    <html lang="en">
      <body>
        <Providers >
          <Layout>{children}</Layout>
        </Providers>

      </body>
    </html>
  );
}
