// app/layout.js
import { getThemeLayout } from "@/theme/themeConfig";
import "./globals.css";
import Providers from "./provider";
import { getTheme } from "@/services/layout";
import { store } from "@/store/store";
import { setTheme } from "@/store/slice/themeSlice";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const data = await getTheme();
  const currentTheme = data?.name || process.env.NEXT_THEME || "theme1";
  const config = data?.config || {};
  const Layout = getThemeLayout(currentTheme);
  return (
    <html lang="en">
      <body style={config}>
        <Providers >
          <Layout theme={{ name: currentTheme, config }}>{children}</Layout>
        </Providers>
      </body>
    </html>
  );
}
